/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  LED_BLINK                              */
/*      FILE         :  typedefine.h                           */
/*      DESCRIPTION  :  Aliases of Integer Type                */
/*      CPU SERIES   :  RL78 - G12                             */
/*      CPU TYPE     :  R5F102AA                               */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                                   
                                                                           
                                                                           
/************************************************************************/
/*    File Version: V1.00                                               */
/*    Date Generated: 10/09/2013                                        */
/************************************************************************/

typedef signed char _SBYTE;
typedef unsigned char _UBYTE;
typedef signed short _SWORD;
typedef unsigned short _UWORD;
typedef signed int _SINT;
typedef unsigned int _UINT;
typedef signed long _SDWORD;
typedef unsigned long _UDWORD;
typedef signed long long _SQWORD;
typedef unsigned long long _UQWORD;
